// <auto-generated />
using System;
using Krunker.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Krunker.DAL.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20201226215431_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Krunker.Common.Models.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceAtPurchase")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a6ca8ca-82c0-4fab-8358-b0023a1b05dd"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("75ccf681-e4b9-4772-97eb-39c61d44ed45"),
                            PriceAtPurchase = 407.88,
                            ShoppingCartId = new Guid("6959a3f5-fe27-43ce-8728-e987f9dde300")
                        },
                        new
                        {
                            Id = new Guid("104d70e3-2ff0-4c0c-8c39-10dd140f7f02"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("6959a3f5-fe27-43ce-8728-e987f9dde300")
                        },
                        new
                        {
                            Id = new Guid("2a5c1d51-0e39-4dff-b38b-73a8350aaa31"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("6959a3f5-fe27-43ce-8728-e987f9dde300")
                        },
                        new
                        {
                            Id = new Guid("5d1e4991-9821-40f8-9979-b2d2b2424425"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("6959a3f5-fe27-43ce-8728-e987f9dde300")
                        },
                        new
                        {
                            Id = new Guid("742cea3d-26d7-4194-8d67-9f2a7b6a9b28"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("75ccf681-e4b9-4772-97eb-39c61d44ed45"),
                            PriceAtPurchase = 407.88,
                            ShoppingCartId = new Guid("d1c2d163-5358-49e1-84c1-9cda5faa2852")
                        },
                        new
                        {
                            Id = new Guid("24c98e31-382a-4739-a31c-c416d4cf78c7"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("d1c2d163-5358-49e1-84c1-9cda5faa2852")
                        },
                        new
                        {
                            Id = new Guid("ba516a6b-96f9-4f7b-8d16-5c8a366977f5"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("d1c2d163-5358-49e1-84c1-9cda5faa2852")
                        },
                        new
                        {
                            Id = new Guid("f41cda4d-8eb2-4613-a3b8-b1e8e9d0c6dc"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("d1c2d163-5358-49e1-84c1-9cda5faa2852")
                        },
                        new
                        {
                            Id = new Guid("4db0e76b-94e5-46d4-bbc8-42f8b61d446d"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("75ccf681-e4b9-4772-97eb-39c61d44ed45"),
                            PriceAtPurchase = 407.88,
                            ShoppingCartId = new Guid("e4c52648-bd1f-4464-991b-7d0083d2c5a1")
                        },
                        new
                        {
                            Id = new Guid("14342f78-40d7-45b9-aafe-cc30fbd1b07a"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("e4c52648-bd1f-4464-991b-7d0083d2c5a1")
                        },
                        new
                        {
                            Id = new Guid("2943ceba-ba6f-4d1d-b22b-00b84e541734"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("e4c52648-bd1f-4464-991b-7d0083d2c5a1")
                        },
                        new
                        {
                            Id = new Guid("a56f5f09-c1c1-47ba-ba53-b313d5e0969c"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("e4c52648-bd1f-4464-991b-7d0083d2c5a1")
                        },
                        new
                        {
                            Id = new Guid("536e69a3-8ab3-4f45-b65c-0ef76cbe132e"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("75ccf681-e4b9-4772-97eb-39c61d44ed45"),
                            PriceAtPurchase = 407.88,
                            ShoppingCartId = new Guid("6053c15c-7316-4405-9eaf-43100e18f514")
                        },
                        new
                        {
                            Id = new Guid("64c854c0-2161-4375-acbc-8feec788a9f0"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("6053c15c-7316-4405-9eaf-43100e18f514")
                        },
                        new
                        {
                            Id = new Guid("e5363cda-54cc-4afe-91bb-9e633fbb22c1"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("6053c15c-7316-4405-9eaf-43100e18f514")
                        },
                        new
                        {
                            Id = new Guid("e051782e-bb37-4281-b2b0-d87a1aa8d774"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("6053c15c-7316-4405-9eaf-43100e18f514")
                        },
                        new
                        {
                            Id = new Guid("55abfc63-936d-49fe-a5a5-ccaf14647620"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("c1b9e69f-3b27-4e5b-bb78-a6c1c83fea11")
                        },
                        new
                        {
                            Id = new Guid("a2683ecf-aa6d-482a-96de-526d6ac66cac"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("c1b9e69f-3b27-4e5b-bb78-a6c1c83fea11")
                        },
                        new
                        {
                            Id = new Guid("cf7f87be-10de-4ad9-9331-b3c2590c8946"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("c1b9e69f-3b27-4e5b-bb78-a6c1c83fea11")
                        },
                        new
                        {
                            Id = new Guid("f1aecddd-83e1-4a1d-8e1c-1361d4853e38"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("c1b9e69f-3b27-4e5b-bb78-a6c1c83fea11")
                        },
                        new
                        {
                            Id = new Guid("700b098c-9852-4835-97a6-d021a0cbc5dc"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("cb20886a-380d-4368-a419-a0c4990ed2d6")
                        },
                        new
                        {
                            Id = new Guid("a09a5fbe-3adb-4be3-b7cd-da2e22127c4e"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4ca15527-db80-4337-8b22-7309c02fe08f"),
                            PriceAtPurchase = 173.25299999999999,
                            ShoppingCartId = new Guid("cb20886a-380d-4368-a419-a0c4990ed2d6")
                        },
                        new
                        {
                            Id = new Guid("1a1a41b7-0d2b-4f98-911f-d69e9e8f1e5d"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("cb20886a-380d-4368-a419-a0c4990ed2d6")
                        },
                        new
                        {
                            Id = new Guid("d1de98fb-5dcc-4c09-b0e7-b658e31c461e"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("1e3994f6-3810-4f38-ad31-6779a169b415"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("cb20886a-380d-4368-a419-a0c4990ed2d6")
                        },
                        new
                        {
                            Id = new Guid("4a8d53fc-4c09-4dd8-941a-5eeafed2e1bc"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("1bb3315e-ee7f-4688-acfa-ca1c5a3f980b")
                        },
                        new
                        {
                            Id = new Guid("477398d5-55b7-4784-8676-84f9cde01cef"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("1bb3315e-ee7f-4688-acfa-ca1c5a3f980b")
                        },
                        new
                        {
                            Id = new Guid("601d30e1-62fa-4363-a0ad-163ad572e297"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("1bb3315e-ee7f-4688-acfa-ca1c5a3f980b")
                        },
                        new
                        {
                            Id = new Guid("4ea35239-613e-443f-ab29-13ca5c16cb37"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("1bb3315e-ee7f-4688-acfa-ca1c5a3f980b")
                        },
                        new
                        {
                            Id = new Guid("d6821127-9a6b-4951-a9e1-2c3639104ce4"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("cf9b6fc3-df40-4cb1-af5c-f1194f468e2c")
                        },
                        new
                        {
                            Id = new Guid("748708f2-e442-4fbb-a8b6-fbcdb77c460b"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("cf9b6fc3-df40-4cb1-af5c-f1194f468e2c")
                        },
                        new
                        {
                            Id = new Guid("f8236fdc-a48d-421d-875b-b0ff43610603"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("cf9b6fc3-df40-4cb1-af5c-f1194f468e2c")
                        },
                        new
                        {
                            Id = new Guid("e080916c-6d0c-4d47-9012-f289c6ed7492"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("cf9b6fc3-df40-4cb1-af5c-f1194f468e2c")
                        },
                        new
                        {
                            Id = new Guid("9eee9ae0-3f95-4b0d-b49f-78190b771002"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("e6227559-7ce3-4816-aad7-6d16dbf5f508")
                        },
                        new
                        {
                            Id = new Guid("5f02c6b4-7c9d-41c7-acae-819976c8619b"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("e6227559-7ce3-4816-aad7-6d16dbf5f508")
                        },
                        new
                        {
                            Id = new Guid("b3087fa3-2abd-48d6-881f-15126c40d255"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("e6227559-7ce3-4816-aad7-6d16dbf5f508")
                        },
                        new
                        {
                            Id = new Guid("861fc8d1-a1cb-4d10-91d9-68359f159d34"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("e6227559-7ce3-4816-aad7-6d16dbf5f508")
                        },
                        new
                        {
                            Id = new Guid("f3d468e4-b8e7-4dee-b8cb-2eb5367dfdd2"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("8ea25f16-137d-4fa7-a9a2-e7fa993e53da")
                        },
                        new
                        {
                            Id = new Guid("39c03902-4f50-49b8-8c38-29c08c68a409"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("8ea25f16-137d-4fa7-a9a2-e7fa993e53da")
                        },
                        new
                        {
                            Id = new Guid("e16a4f7e-0ebd-48dd-81c8-6b1cbc0e5a73"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("8ea25f16-137d-4fa7-a9a2-e7fa993e53da")
                        },
                        new
                        {
                            Id = new Guid("f89f9282-ab72-4867-9064-32a2d1086f37"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("8ea25f16-137d-4fa7-a9a2-e7fa993e53da")
                        },
                        new
                        {
                            Id = new Guid("9c88ec30-db42-4e3d-af39-9913fc6fa8ba"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("0735abdb-1fa2-4598-bb01-2ac4afffa251")
                        },
                        new
                        {
                            Id = new Guid("07dec7b8-01c0-4d35-aa68-02fce38a5ca0"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("0735abdb-1fa2-4598-bb01-2ac4afffa251")
                        },
                        new
                        {
                            Id = new Guid("f2317c36-5f7a-464e-a110-e663abe51a03"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("0735abdb-1fa2-4598-bb01-2ac4afffa251")
                        },
                        new
                        {
                            Id = new Guid("674e6300-3731-461d-b0ca-bae324f6a59a"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("0735abdb-1fa2-4598-bb01-2ac4afffa251")
                        },
                        new
                        {
                            Id = new Guid("da3ba1d7-c379-4bd6-b34b-e3482a6863f0"),
                            Amount = 1,
                            DiscountRate = 12.0,
                            ItemId = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            PriceAtPurchase = 714.73612379999997,
                            ShoppingCartId = new Guid("7ea669b1-c896-472a-b3ae-441ab6d53012")
                        },
                        new
                        {
                            Id = new Guid("dd908313-1759-45ab-9f35-15c3b9eac4f4"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            PriceAtPurchase = 144.18700000000001,
                            ShoppingCartId = new Guid("7ea669b1-c896-472a-b3ae-441ab6d53012")
                        },
                        new
                        {
                            Id = new Guid("72fadb97-c054-4b23-a702-5cbdb3463247"),
                            Amount = 1,
                            DiscountRate = 50.0,
                            ItemId = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            PriceAtPurchase = 612.45609999999999,
                            ShoppingCartId = new Guid("7ea669b1-c896-472a-b3ae-441ab6d53012")
                        },
                        new
                        {
                            Id = new Guid("600902e5-4104-40d6-af7e-9338482b3ad2"),
                            Amount = 1,
                            DiscountRate = 0.0,
                            ItemId = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            PriceAtPurchase = 84.515600000000006,
                            ShoppingCartId = new Guid("7ea669b1-c896-472a-b3ae-441ab6d53012")
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PurchaseComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6959a3f5-fe27-43ce-8728-e987f9dde300"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 46, 850, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1126.5983679999999
                        },
                        new
                        {
                            Id = new Guid("d1c2d163-5358-49e1-84c1-9cda5faa2852"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 47, 50, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1126.5983679999999
                        },
                        new
                        {
                            Id = new Guid("e4c52648-bd1f-4464-991b-7d0083d2c5a1"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 47, 750, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1126.5983679999999
                        },
                        new
                        {
                            Id = new Guid("6053c15c-7316-4405-9eaf-43100e18f514"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 47, 820, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1126.5983679999999
                        },
                        new
                        {
                            Id = new Guid("c1b9e69f-3b27-4e5b-bb78-a6c1c83fea11"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 57, 820, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1396.631756944
                        },
                        new
                        {
                            Id = new Guid("cb20886a-380d-4368-a419-a0c4990ed2d6"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 58, 820, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1386.2528449439999
                        },
                        new
                        {
                            Id = new Guid("1bb3315e-ee7f-4688-acfa-ca1c5a3f980b"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 14, 59, 920, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1396.631756944
                        },
                        new
                        {
                            Id = new Guid("cf9b6fc3-df40-4cb1-af5c-f1194f468e2c"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 15, 8, 420, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1396.631756944
                        },
                        new
                        {
                            Id = new Guid("e6227559-7ce3-4816-aad7-6d16dbf5f508"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 16, 28, 420, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1396.631756944
                        },
                        new
                        {
                            Id = new Guid("8ea25f16-137d-4fa7-a9a2-e7fa993e53da"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 16, 35, 420, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1470.1264889439999
                        },
                        new
                        {
                            Id = new Guid("0735abdb-1fa2-4598-bb01-2ac4afffa251"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 18, 15, 980, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1470.1264889439999
                        },
                        new
                        {
                            Id = new Guid("7ea669b1-c896-472a-b3ae-441ab6d53012"),
                            PurchaseComplete = true,
                            PurchaseTime = new DateTime(1, 1, 2, 20, 26, 35, 980, DateTimeKind.Unspecified).AddTicks(6973),
                            TotalPrice = 1163.898438944
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.ShoppingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("UriImg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ShoppingItem");
                });

            modelBuilder.Entity("Krunker.Common.Models.BackItem", b =>
                {
                    b.HasBaseType("Krunker.Common.Models.ShoppingItem");

                    b.Property<bool>("IsWings")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("BackItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1af020e5-fa5f-4fc3-aa6b-10ba2ea8c210"),
                            Archived = false,
                            CurrentAmount = 10,
                            Discount = 0,
                            Name = "Diablo Wings",
                            Price = 630.23000000000002,
                            UriImg = "BackItem/DiabloWings.png",
                            IsWings = true
                        },
                        new
                        {
                            Id = new Guid("75ccf681-e4b9-4772-97eb-39c61d44ed45"),
                            Archived = false,
                            CurrentAmount = 10,
                            Discount = 0,
                            Name = "Panda Body",
                            Price = 407.88,
                            UriImg = "BackItem/PandaBody.png",
                            IsWings = false
                        },
                        new
                        {
                            Id = new Guid("b2a90bde-23b2-49a5-bf03-499f2c079a5e"),
                            Archived = false,
                            CurrentAmount = 10,
                            Discount = 0,
                            Name = "Angeilc Wings",
                            Price = 580.92409999999995,
                            UriImg = "BackItem/AngeilcWings.png",
                            IsWings = true
                        },
                        new
                        {
                            Id = new Guid("4b4bc481-6362-4a50-990f-97870cd5f61e"),
                            Archived = false,
                            CurrentAmount = 10,
                            Discount = 0,
                            Name = "Samurai Blades",
                            Price = 714.73612379999997,
                            UriImg = "BackItem/SamuraiBlades.png",
                            IsWings = false
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.HeadItem", b =>
                {
                    b.HasBaseType("Krunker.Common.Models.ShoppingItem");

                    b.HasDiscriminator().HasValue("HeadItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac5121c3-6215-4475-8c2c-9559dec2db4d"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Afro",
                            Price = 144.18700000000001,
                            UriImg = "HeadItem/Afro.png"
                        },
                        new
                        {
                            Id = new Guid("4ca15527-db80-4337-8b22-7309c02fe08f"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Bandit",
                            Price = 173.25299999999999,
                            UriImg = "HeadItem/Bandit.png"
                        },
                        new
                        {
                            Id = new Guid("e51aff66-9d59-4327-87b8-dec4b8f7b125"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Clown",
                            Price = 94.644999999999996,
                            UriImg = "HeadItem/Clown.png"
                        },
                        new
                        {
                            Id = new Guid("462cd6fb-7a69-4ed2-a74e-477e16519c16"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Diuer Goggles",
                            Price = 97.412000000000006,
                            UriImg = "HeadItem/DiuerGoggles.png"
                        },
                        new
                        {
                            Id = new Guid("daec6e75-1e0c-4039-ad62-b49d96a0807f"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Jack o' Lantern",
                            Price = 170.98140000000001,
                            UriImg = "HeadItem/JackLantern.png"
                        },
                        new
                        {
                            Id = new Guid("944f109e-d36e-4679-bc59-9c0db7148c0e"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Mad Cap",
                            Price = 86.344999999999999,
                            UriImg = "HeadItem/MadCap.png"
                        },
                        new
                        {
                            Id = new Guid("062c2c92-390e-4df6-bddf-26f40ccde370"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "MadMan",
                            Price = 134.25299999999999,
                            UriImg = "HeadItem/Madman.png"
                        },
                        new
                        {
                            Id = new Guid("11bb3e65-595a-473f-8171-e6ce9984bebe"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Pig Head",
                            Price = 48.606000000000002,
                            UriImg = "HeadItem/PigHead.png"
                        },
                        new
                        {
                            Id = new Guid("5b28fd2c-5d2e-4fa0-a3de-0617af5eff19"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Sun Glasses",
                            Price = 103.712,
                            UriImg = "HeadItem/SunGlasses.png"
                        },
                        new
                        {
                            Id = new Guid("f78cdb47-44df-4e40-b6bb-148165c8d50b"),
                            Archived = false,
                            CurrentAmount = 120,
                            Discount = 0,
                            Name = "Zombie Head",
                            Price = 230.87423000000001,
                            UriImg = "HeadItem/ZombieHead.png"
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.PrimaryWeapon", b =>
                {
                    b.HasBaseType("Krunker.Common.Models.ShoppingItem");

                    b.Property<int>("AmountBalls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Automatic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrimaryWeapon_Automatic");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT")
                        .HasColumnName("PrimaryWeapon_Creator");

                    b.Property<int>("FirePower")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrimaryWeapon_FirePower");

                    b.Property<double>("ShootingRange")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrimaryWeapon_Year");

                    b.HasDiscriminator().HasValue("PrimaryWeapon");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78e0e6d9-02a8-46fa-8135-5891ac904db2"),
                            Archived = false,
                            CurrentAmount = 88,
                            Discount = 0,
                            Name = "Aqua",
                            Price = 612.45609999999999,
                            UriImg = "PrimaryWeapons/Aqua.png",
                            AmountBalls = 35,
                            Automatic = true,
                            Creator = "IDF",
                            FirePower = 478,
                            ShootingRange = 890.17700000000002,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("f769e2f8-edd9-4ee6-b884-930d25865d89"),
                            Archived = false,
                            CurrentAmount = 50,
                            Discount = 0,
                            Name = "Cherry Blossom",
                            Price = 456.613,
                            UriImg = "PrimaryWeapons/CherryBlossom.png",
                            AmountBalls = 29,
                            Automatic = true,
                            Creator = "Jhonny Depp",
                            FirePower = 225,
                            ShootingRange = 5006.3000000000002,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("e6d83d26-9d48-41d0-9d24-a36f484d354c"),
                            Archived = false,
                            CurrentAmount = 50,
                            Discount = 0,
                            Name = "Commo",
                            Price = 650.10045600000001,
                            UriImg = "PrimaryWeapons/Commo.png",
                            AmountBalls = 60,
                            Automatic = true,
                            Creator = "USA",
                            FirePower = 123,
                            ShootingRange = 5504.1999999999998,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("4ea88879-6716-4182-b0a4-cd9434dab5a4"),
                            Archived = false,
                            CurrentAmount = 45,
                            Discount = 0,
                            Name = "Dijon",
                            Price = 336.23000000000002,
                            UriImg = "PrimaryWeapons/Dijon.png",
                            AmountBalls = 29,
                            Automatic = true,
                            Creator = "France",
                            FirePower = 420,
                            ShootingRange = 5050.1199999999999,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("7dc6bbb8-2e78-4fc2-a29a-981e55007777"),
                            Archived = false,
                            CurrentAmount = 31,
                            Discount = 0,
                            Name = "Interuention Ul",
                            Price = 525.71799999999996,
                            UriImg = "PrimaryWeapons/InteruentionUl.png",
                            AmountBalls = 5,
                            Automatic = false,
                            Creator = "IDF",
                            FirePower = 1050,
                            ShootingRange = 15000.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("596e7611-6ea3-446d-89ad-4b976404e846"),
                            Archived = false,
                            CurrentAmount = 30,
                            Discount = 0,
                            Name = "LMG Wanderer",
                            Price = 850.14700000000005,
                            UriImg = "PrimaryWeapons/LMGWanderer.png",
                            AmountBalls = 5,
                            Automatic = true,
                            Creator = "Voca People",
                            FirePower = 630,
                            ShootingRange = 456.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("13becbc4-a6f3-47bb-91b6-ec3716373571"),
                            Archived = false,
                            CurrentAmount = 48,
                            Discount = 0,
                            Name = "Puma RR",
                            Price = 472.45468399999999,
                            UriImg = "PrimaryWeapons/PumaRR.png",
                            AmountBalls = 5,
                            Automatic = false,
                            Creator = "Iraq",
                            FirePower = 1050,
                            ShootingRange = 250.80000000000001,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("423c95f9-3e68-4ade-ab18-21e40f8ae5fe"),
                            Archived = false,
                            CurrentAmount = 4,
                            Discount = 0,
                            Name = "Spectrum",
                            Price = 1322.9423509999999,
                            UriImg = "PrimaryWeapons/Spectrum.png",
                            AmountBalls = 5,
                            Automatic = false,
                            Creator = "India",
                            FirePower = 983,
                            ShootingRange = 149.40000000000001,
                            Year = 1987
                        },
                        new
                        {
                            Id = new Guid("6ac75aad-9f02-4fbc-bcb0-12d48bd87cbe"),
                            Archived = false,
                            CurrentAmount = 12,
                            Discount = 0,
                            Name = "Theta",
                            Price = 1048.7235229999999,
                            UriImg = "PrimaryWeapons/Theta.png",
                            AmountBalls = 37,
                            Automatic = false,
                            Creator = "USA",
                            FirePower = 945,
                            ShootingRange = 15008.0,
                            Year = 2018
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.SecondaryWeapon", b =>
                {
                    b.HasBaseType("Krunker.Common.Models.ShoppingItem");

                    b.Property<bool>("Automatic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnifeLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeKnife")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("SecondaryWeapon");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb415d68-8d73-4135-90a4-e02cc7d66dd5"),
                            Archived = false,
                            CurrentAmount = 103,
                            Discount = 0,
                            Name = "Flame Fang",
                            Price = 84.515600000000006,
                            UriImg = "SecondaryWeapons/FlameFang.png",
                            Automatic = false,
                            Creator = "Idan Amedi",
                            FirePower = 20,
                            KnifeLength = 12,
                            TypeKnife = 0,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("675f5421-1641-403a-b967-b1548496fc20"),
                            Archived = false,
                            CurrentAmount = 97,
                            Discount = 0,
                            Name = "Soul Fang",
                            Price = 126.9753,
                            UriImg = "SecondaryWeapons/SoulFang.png",
                            Automatic = false,
                            Creator = "Idan Raichel",
                            FirePower = 58,
                            KnifeLength = 16,
                            TypeKnife = 1,
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("1e3994f6-3810-4f38-ad31-6779a169b415"),
                            Archived = false,
                            CurrentAmount = 86,
                            Discount = 0,
                            Name = "Uolt Fang",
                            Price = 74.842100000000002,
                            UriImg = "SecondaryWeapons/UoltFang.png",
                            Automatic = false,
                            Creator = "Idan Naim",
                            FirePower = 36,
                            KnifeLength = 12,
                            TypeKnife = 1,
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Krunker.Common.Models.Purchase", b =>
                {
                    b.HasOne("Krunker.Common.Models.ShoppingItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krunker.Common.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("Purchases")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Krunker.Common.Models.ShoppingCart", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Krunker.Common.Models.ShoppingItem", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
